BookStore.WebUI/BookStore.WebUI/Controllers/BookController.cs
using BookStore.Domain.Abstract;
using BookStore.Domain.Entities;
using BookStore.WebUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BookStore.WebUI.Controllers
{
    public class BookController : Controller
    {
        //
        private IBookRepository repository;
        
        public int PageSize = 4;
        public BookController(IBookRepository bookRep)
        {
            repository = bookRep;
        }
        
        
        //a5ly ell parameter el egbarya daymn elawal specilization
        public ViewResult List(string specilization, int pageno=1)
        {
            

            BookListViewModel model =
                new BookListViewModel
                {
                    Books = repository.Books
                    .Where(b=>specilization == null || b.Specialization == specilization)
                    .OrderBy(b => b.ISBN)
                    .Skip((pageno - 1) * PageSize)
                    .Take(PageSize).ToList(), 
                     PagingInfo = new Models.PagingInfo 
                     {
                         CurrentPage = pageno,
                         ItemsPerPage = PageSize,
                         TotalItems = specilization==null? 
                                                        repository.Books.Count():
                                                        repository.Books.Where(b=>b.Specialization==specilization).Count()
                     },
                     CurrentSpecilization = specilization
                     
                };
            return View(model);
        }

        public FileContentResult GetImage(int isbn)
        {
            Book book = repository.Books
            .FirstOrDefault(p => p.ISBN == isbn);
            if (book != null)
            {
                //ImageMimeType the type of the image
                return File(book.ImageData, book.ImageMimeType);
            }
            else
            {
                return null;
            }
        }
        public ViewResult ListAll()
        {
            //return View(repository.Books.FirstOrDefault());//34an da list
            return View(repository.Books.ToList());//34an da list
        }
	}
}

BookStore.WebUI/BookStore.WebUI/Controllers/CartController.cs
using BookStore.Domain.Abstract;
using BookStore.Domain.Entities;
using BookStore.WebUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BookStore.WebUI.Controllers
{
    public class CartController : Controller
    {

        private IBookRepository repository;
        private IOrderProcessor orderProcessor;
        public CartController(IBookRepository repo,IOrderProcessor proc)
        {
            repository = repo;
            orderProcessor = proc;
        }

        public ViewResult Index(Cart cart, string returnUrl)
        {
            return View(new CartIndexViewModel
            {
                Cart = cart,
                ReturnUrl = returnUrl
            });
        }

        public RedirectToRouteResult AddToCart(Cart cart, int isbn, string returnUrl)
        {
            Book book=repository.Books.FirstOrDefault(b=>b.ISBN==isbn);
            if(book!=null)
            {
                //getcart().additem(book);
                cart.AddItem(book);
            }

            return RedirectToAction("Index", new { returnUrl }); //Index
        }

        public RedirectToRouteResult RemoveFromCart(Cart cart, int isbn, string returnUrl)
        {
            Book book = repository.Books.FirstOrDefault(b => b.ISBN == isbn);
            if (book != null)
            {
                cart.RemoveLine(book);
                //getcart().removeline(book);
            }

            return RedirectToAction("Index", new { returnUrl }); //Index
        }
        //mmok a7tag a7zfha
        //public  Cart GetCart()
        //{
        //    Cart cart =(Cart) Session["Cart"];
        //    if(cart==null)
        //    {
        //        cart = new Cart();
        //        Session["Cart"] = cart;
                
        //    }
        //    return cart;
            
        //}

        public PartialViewResult Summary(Cart cart)
        {
            return PartialView(cart);
        }

        public ViewResult Checkout()
        {
            return View(new ShippingDetails());
        }
        [HttpPost]
        public ViewResult Checkout(Cart cart,ShippingDetails shippingDetails)
        {
            if (cart.Lines.Count() == 0)
                ModelState.AddModelError("", "Sorry your cart is empty");
            if(ModelState.IsValid)
            {
                orderProcessor.SaveOrder(shippingDetails);
               
                orderProcessor.ProcessOrder(cart, shippingDetails);
                cart.Clear();
                return View("Completed");
            }else
                //shipingDetails elly hea mab3otaly
                return View(shippingDetails);
        }

	}
}

//if(ModelState.IsValid)
//            {
//                repository.SaveBook(book);
//                //7aga 4bh el session leha w2t w ynthy
//                TempData["message"] = book.Title + "has been saved";
//                return RedirectToAction("Index");

//            }
//            else
//            {
//                return View(book);
//            }

BookStore.WebUI/BookStore.WebUI/Controllers/NavController.cs
using BookStore.Domain.Abstract;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BookStore.WebUI.Controllers
{
    public class NavController : Controller
    {
        private IBookRepository repository;

        public NavController(IBookRepository repo)
        {
            repository = repo;
        }

        public PartialViewResult Menu(string specilization = null)
        {
            ViewBag.SelectedSpec = specilization;
            IEnumerable<string> spec = repository.Books
                .Select(b => b.Specialization)
                .Distinct();  //bt4el el tekrar
           // string viewName = mobileLayout ? "MenuHorizontal" : "Menu";
            return PartialView("FlexMenu",spec);
        }
	}
}

BookStore.WebUI/BookStore.WebUI/Views/Shared/BookSummary.Mobile.cshtml
@model BookStore.Domain.Entities.Book

<div data-role="collapsible" data-collapsed="false" data-content-theme="c">
    <h2>
        <strong>@Model.Title</strong>

    </h2>
    <div class="ui-grid-b">
        <div class="ui-block-a">
            @Model.Description
        </div>
        <div class="ui-block-b">
            <strong>@Model.Price.ToString("c")</strong>
        </div>
        <div class="ui-block-c">
            @using (Html.BeginForm("AddToCart", "Cart"))
            {

                    @Html.HiddenFor(b => b.ISBN)
                    @*//hatlob kol el7agat elly mawgwoda f el saf7a fo2*@
                    @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
                <input type="submit"  data-inline="true"  data-mini="true" value="Add To Cart" />
              
            }

        </div>
    </div>
    @*<span class="lead">@Model.Description</span>*@

</div>

BookStore.WebUI/BookStore.WebUI/Views/Shared/BookSummary.cshtml
@model BookStore.Domain.Entities.Book

<div class="well">

        @if (Model.ImageData != null)
        {
            <div class="pull-left" style="margin-right: 10px">
                <img class="img-thumbnail" width="75" height="75"
                     src="@Url.Action("GetImage", "Book",
         new { Model.ISBN })" />
            </div>
        }

    <h3>
        <strong>@Model.Title</strong>
        <span class="pull-right label label-primary">@Model.Price.ToString("c") </span>
    </h3>
    @*<span class="lead">@Model.Description</span>*@
    @using(Html.BeginForm("AddToCart","Cart"))
    {
        <div class="">
            <input type="submit" class="btn btn-success" value="Add To Cart" />
            @Html.HiddenFor(b=>b.ISBN)
            @*//hatlob kol el7agat elly mawgwoda f el saf7a fo2*@
            @*//34an lma arg3 arg3 la5r mkan ana kont feh m4 atla3 bra 5ales*@
            @Html.Hidden("returnUrl",Request.Url.PathAndQuery)
         </div>
    }


</div>

BookStore.WebUI/BookStore.WebUI/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <link href="~/Content/ErrorStyle.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.9.1.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
</head>
<body>
    <div>
        @if(TempData["message"] !=null)
        {
            <div class="alert alert-success">@TempData["message"]</div>
        }
        @RenderBody()
    </div>
</body>
</html>

BookStore.WebUI/BookStore.WebUI/Views/Shared/_Layout.Mobile.cshtml
<!DOCTYPE html>

<html>
<head>
    <title>@ViewBag.Title</title>
    <meta name="viewport" content="width=device-width; "  />
    <script src="~/Scripts/jquery-1.9.1.min.js"></script>
    <link rel="stylesheet" href="~/ Content/jquery.mobile-1.3.2.min.css" />
    @*<link rel="stylesheet" href="http://code.jquery.com/mobile/1.3.2/jquery.mobile-1.3.2.min.css"/>
    <script src="http://code.jquery.com/mobile/1.3.2/jquery.mobile-1.3.2.min.css"></script>*@
    
    <script src="~/Scripts/jquery.mobile-1.3.2.min.js"></script>
</head>

<body>
    <div>
        @*wazeft el data*@
        <div data-role="page" id="page1">
            <div data-theme="a" data-role="header" data-position="fixed">
                <h3>Bookstor</h3>
                @Html.Action("Menu","Nav")
            </div>
            <div data-role="content">
                <ul data-role="listview" data-divider-theme="b" data-inset="false">
                    @RenderBody()

                </ul>
            </div>

        </div>
        
    </div>
</body>
</html>

BookStore.WebUI/BookStore.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title </title>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet"/>
    <link href="~/Content/ErrorStyle.css" rel="stylesheet" />
    <style>

        .navbar-right {
            /*leh el awlayea f eltanfez bsbb important*/ 
             float:right !important;
            margin-right: 20px;
            margin-left: 15px;
        }
    </style>
</head>
<body>
    <div class="navbar navbar-inverse" role="navigation">
        <a class="navbar-brand" href="#">
            @*ha5feha f 7alt elaghza elso8ira*@
            <span class="hidden-xs">Book Store</span> 
            @*hazhrhom f 7alt elaghza elso8ira*@
            <div class="visible-xs">Book</div>
            <div class="visible-xs">Store</div>
        </a>
        @Html.Action("Summary", "Cart")
    </div>
    <div class="visible-xs">
        @Html.Action("Menu", "Nav", new  { mbileLayout = true })
    </div>
    <div class="row panel" >
        <div id="specialization" class="col-xs-3 hidden-xs">
            @Html.Action("Menu","Nav")
        </div>
        <div class="col-xs-12 col-sm-8">
            @RenderBody()
        </div>
    </div>

        
      
</body>
</html>