BookStore.WebUI/BookStore.WebUI/Controllers/AdminController.cs
using BookStore.Domain.Abstract;
using BookStore.Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BookStore.WebUI.Controllers
{
    [Authorize]
    public class AdminController : Controller
    {
        private IBookRepository repository;
        public AdminController(IBookRepository repo)
        {
            repository = repo;
        }

        //mogard 3rd
        public ViewResult Index()
        {
            return View(repository.Books);
        }
        public ViewResult Edit(int ISBN)
        {
            Book book = repository.Books.FirstOrDefault(b => b.ISBN == ISBN);
            return View(book);
        }
        [HttpPost]
        public ActionResult Edit(Book book , HttpPostedFileBase image = null)
        {
            //bt2kd en el data salema
            if(ModelState.IsValid)
            {
                if (image != null)
                {
                    book.ImageMimeType =  image.ContentType;
                    book.ImageData = new byte[image.ContentLength];
                    image.InputStream.Read(book.ImageData, 0, image.ContentLength);
                }
                repository.SaveBook(book);
                //7aga 4bh el session leha w2t w ynthy
                TempData["message"] = book.Title + "has been saved";
                return RedirectToAction("Index");

            }
            else
            {
                return View(book);
            }
        }
        public ViewResult Create()
        {
            return View("Edit", new Book());
        }
        [HttpGet]
        public ActionResult Delete(int ISBN)
        {
            Book deletedBook = repository.DeleteBook(ISBN);
            if(deletedBook !=null)
            {
                TempData["message"] = deletedBook.Title + "was deleted";
            }
            return RedirectToAction("Index");
        }
	}
}

BookStore.WebUI/BookStore.WebUI/Controllers/BookController.cs
using BookStore.Domain.Abstract;
using BookStore.Domain.Entities;
using BookStore.WebUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BookStore.WebUI.Controllers
{
    public class BookController : Controller
    {
        //
        private IBookRepository repository;
        
        public int PageSize = 4;
        public BookController(IBookRepository bookRep)
        {
            repository = bookRep;
        }
        
        
        //a5ly ell parameter el egbarya daymn elawal specilization
        public ViewResult List(string specilization, int pageno=1)
        {
            

            BookListViewModel model =
                new BookListViewModel
                {
                    Books = repository.Books
                    .Where(b=>specilization == null || b.Specialization == specilization)
                    .OrderBy(b => b.ISBN)
                    .Skip((pageno - 1) * PageSize)
                    .Take(PageSize).ToList(), 
                     PagingInfo = new Models.PagingInfo 
                     {
                         CurrentPage = pageno,
                         ItemsPerPage = PageSize,
                         TotalItems = specilization==null? 
                                                        repository.Books.Count():
                                                        repository.Books.Where(b=>b.Specialization==specilization).Count()
                     },
                     CurrentSpecilization = specilization
                     
                };
            return View(model);
        }

        public FileContentResult GetImage(int isbn)
        {
            Book book = repository.Books
            .FirstOrDefault(p => p.ISBN == isbn);
            if (book != null)
            {
                //ImageMimeType the type of the image
                return File(book.ImageData, book.ImageMimeType);
            }
            else
            {
                return null;
            }
        }
        public ViewResult ListAll()
        {
            //return View(repository.Books.FirstOrDefault());//34an da list
            return View(repository.Books.ToList());//34an da list
        }
	}
}

BookStore.WebUI/BookStore.WebUI/Views/Admin/Edit.cshtml
@model BookStore.Domain.Entities.Book
@{
    ViewBag.Title =Model.Title;
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    //34an a5ly el Client validatition hwa elly y4t5l
    HtmlHelper.ClientValidationEnabled = false;
    HtmlHelper.UnobtrusiveJavaScriptEnabled = false;
}
<div class="panel">
    <div class="panel-heading">
        <h3>Edit @Model.Title</h3>


    </div>

    @using (Html.BeginForm("Edit", "Admin", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
        <div class="panel-body">
            @Html.HiddenFor(b=>b.ISBN)
            @foreach(var property in ViewData.ModelMetadata.Properties)
        {
                

            if(property.PropertyName!="ISBN")
            {
                                 switch (property.PropertyName) {
                case "ProductID":
                case "ImageData":
                case "ImageMimeType":
                // do nothing
                break;
                default:
                <div class="form-group">
                    <label>@(property.DisplayName?? property.PropertyName)</label>
                    @if(property.PropertyName=="Description")
                    {
                        @Html.TextArea(property.PropertyName,null,new{@class="form-control",rows=5})
                    }
                    else
                    {
                        @Html.TextBox(property.PropertyName,null,new{@class="form-control"})
                    }
                    @*hena hay3rd el messages*@
                    @Html.ValidationMessage(property.PropertyName)
                </div>
            break;
            }
        }
        }  
        <div class="form-group">
        <div style="position:relative;">
        <label>Image</label>
        <a class='btn' href='javascript:;'>
        Choose File...
        <input type="file" name="Image" size="40"
        style="position:absolute;z-index:2;top:0;
        left:0;filter: alpha(opacity=0); opacity:0;
        background-color:transparent;color:transparent;"
        onchange='$("#upload-file-info").html($(this).val());'>
        </a>
        <span class='label label-info' id="upload-file-info"></span>
        </div>
        @if (Model.ImageData == null) {
        <div class="form-control-static">No Image</div>
            } else {
        <img class="img-thumbnail" width="150" height="150"
        src="@Url.Action("GetImage", "Book",
        new { Model.ISBN })" />
        }
</div>
            
        </div>
        @*hay3ml el form kolha automatic
            @Html.EditorForModel();*@
        <div class="panel-footer">
            <input type="submit" value="save" class="btn btn-primary" />
            @Html.ActionLink("Cancel and return to list", "Index",null,new{@class="btn btn-default"})
        </div>


    }

</div>

BookStore.WebUI/BookStore.WebUI/Views/Admin/Index.cshtml
@model IEnumerable<BookStore.Domain.Entities.Book>

@{
    ViewBag.Title = "Index : All Books";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Book Index</h2>
<div class="panel panel-default">
    <div class="panel-heading">
        <h3>All Books</h3>
    </div>
    <div class="panel-body">

        <table class="table table-condensed table-striped table-bordered">
            <tr>
                <th class="text-right">
                    @Html.DisplayNameFor(model => model.ISBN)
                </th>
                <th >
                    @Html.DisplayNameFor(model => model.Title)
                </th>
                <th >
                    @Html.DisplayNameFor(model => model.Description)
                </th>
                <th class="text-right">
                    @Html.DisplayNameFor(model => model.Price)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Specialization)
                </th>
                
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td class="text-right">
                        @Html.DisplayFor(modelItem => item.ISBN)
                    </td>
                    <td class="">
                        @Html.ActionLink(item.Title, "Edit", new { item.ISBN })
                        
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Description)
                    </td>
                    <td class="text-right">
                        @*@Html.DisplayFor(modelItem => item.Price)*@
                        @item.Price.ToString("c")
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Specialization)
                    </td>
                    <td class="text-center">
                        @*@Html.ActionLink("Edit", "Edit", new { id = item.ISBN }) |
                        @Html.ActionLink("Details", "Details", new { id = item.ISBN }) |*@
                        @Html.ActionLink("Delete", "Delete", new {item.ISBN }, new  { @class="btn btn-danger btn-xs"})
                    </td>
                </tr>
            }

        </table>

    </div>
    <div class="panel-footer">
        @Html.ActionLink("Add New Book", "Create", null, new {@class="btn btn-default" })
    </div>
</div>

   @*<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Specialization)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Specialization)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ISBN }) |
            @Html.ActionLink("Details", "Details", new { id=item.ISBN }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ISBN })
        </td>
    </tr>
}

</table>*@